version: "3.0"
services:
  web:
    restart: unless-stopped
    image: projectsend:r1335
    volumes:
      - /opt/projectsend/config:/config
      - /opt/projectsend/data:/data
    ports:
      - "8080:80"
  mysql:
    restart: unless-stopped
    image: mariadb:10.7
    volumes:
      - /opt/mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projectsend
      MYSQL_USER: projectsend
      MYSQL_PASSWORD: projectsend